### ISSUE TITLE
BotState.SAFE needs to be split up

### ISSUE THREAD

**Issue by lorenzorota** [iRath96/splix-bot#1]
[![IMAGE ALT TEXT](http://img.youtube.com/vi/raSDR-SWnyE/0.jpg)](http://www.youtube.com/watch?v=raSDR-SWnyE "Video Title")

**Comment by iRath96** [comment]
**This is what causes the bug:**

1. `BotState.ADVANCING`
2. `BotState.PRE_RETURN`
3. `BotState.SAFE`
4. `BotState.ADVANCING`

**How to fix this bug:**
The bot should not be able to go from any advancing state (`ADVANCE`, `PRE_RETURN` and `RETURNING`) to the `SAFE` state. There should be a dedicated `SAFE_RETURN` state to differentiate between being safe (on ones own block) and returning safely.
