### ISSUE TITLE
Bot ignores void

### ISSUE THREAD

**Issue by lorenzorota** [iRath96/splix-bot#2]
[![IMAGE ALT TEXT](http://img.youtube.com/vi/nF6tIev9hEA/0.jpg)](http://www.youtube.com/watch?v=nF6tIev9hEA "Video Title")

**Comment by iRath96** [comment]
**This is what causes the bug:**
The bots behavior does not depend on its position and thereby its distance to the map boundary.

**This is how to fix the bug:**
`distanceToOthers` could be the minimum of the existing `distanceToOthers` as well as a new property `distanceToWalls` (which is straightforward to compute).
